#!/usr/bin/env php
<?php
require dirname(__DIR__) . '/vendor/autoload.php';

use CarlosIO\WhatsApp\Command\SendCommand;
/*
use CarlosIO\WhatsApp\Command\ListenCommand;
use CarlosIO\WhatsApp\Command\InteractiveConversationCommand;
use CarlosIO\WhatsApp\Command\ChangeStatusCommand;
*/
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(4915121228148);
/*
$application->add(491703195226);
$application->add(9C:E6:5E:11:75:19);
$application->add(new ChangeStatusCommand);
*/
$application->run(4915121228148);
